version: '3.4'

x-webapp-template: &webapp-template
  build: .
  # We have to use the host network mode to make sure that the URLs for object
  # storage which appear in the web interface match the ones the server uses.
  network_mode: host
  expose:
    - "8000"
  env_file:
    - ./env/webapp.env

services:
  # The web application itself
  webapp:
    <<: *webapp-template

  # Convenience service to make sure the latest database migrations are applied.
  webapp_migrate:
    <<: *webapp-template
    # HACK: we sleep to give the database time to come up
    entrypoint: ['sh', '-c', 'sleep 5 && ./manage.py migrate']
